name: ci

on: [push, pull_request]

env:
  PKG_NAME: fns

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test --parallel --enable-code-coverage -v

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: latest-stable
      
      - name: Export Code Coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/${{ env.PKG_NAME }}PackageTests.xctest/Contents/MacOS/${{ env.PKG_NAME }}PackageTests -instr-profile .build/debug/codecov/default.profdata > code-coverage.lcov

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./code-coverage.lcov
          verbose: true

      
